---
title: "linear regression for temporal context tapping data"
output: html_document
date: "2023-06-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(lme4)
library(lmerTest)
library(car)
library(magrittr)
library(patchwork)
library(emmeans)
library(knitr)


```


```{r load_data, echo=FALSE}

data_df = read.csv("levantar_datos/data_GroupSubjCond_OS_df.csv")
dict_df = read.csv("levantar_datos/data_GroupSubjCond_OS_dict.csv")



```

```{r rearrange_data, echo=FALSE}

DeltaT <- 50

# select relevant data
data2_df <- data_df %>%
			select('Exp_name','General_condition','Subject',
				   'Relative_beep','mean_asyn') %>%
			rename(beep=Relative_beep, asyn=mean_asyn) %>%
			mutate(subject = if_else(Exp_name=='Experiment_PS', Subject+100, # make subject unique
									 if_else(Exp_name=='Experiment_SC', Subject+200, Subject+300)),
				   context = if_else(Exp_name=='Experiment_PS_SC', 'comb', 'pure')) # define context

# add missing data
data3_df <- inner_join(
				data2_df,
				dict_df[,c('General_condition','Name','Perturb_type','Perturb_size')],
				by='General_condition') %>%
			filter(Perturb_size==50 | Perturb_size==-50) %>%
			mutate(perturb_type = if_else(Perturb_type==0, 'SC', 'PS'),
				   perturb_sign = if_else(Perturb_size==50, 'pos', 'neg'),
				   pred_asyn = case_when(
				   					# SC and PS cases
				   					beep==0 & perturb_sign=='pos' ~ asyn+DeltaT,
				   					beep==0 & perturb_sign=='neg' ~ asyn-DeltaT,
				   					# PS cases
				   					beep==1 & perturb_type=='PS'& perturb_sign=='pos' ~ asyn-DeltaT,
				   					beep==1 & perturb_type=='PS'& perturb_sign=='neg' ~ asyn+DeltaT,
				   					TRUE ~ asyn)
				   ) %>%
			# drop unused columns
			select(-c('Exp_name','General_condition','Perturb_type','Perturb_size','Name','Subject')) %>%
			# reorder columns
			select(c('context','perturb_type','perturb_sign','subject','beep','asyn','pred_asyn'))

# define limits of resynchronization phase (beeps)
resynch_start <- 1
resynch_end <- 6

```

```{r average_data, echo=FALSE}

# average original data
data3_mean_df <- data3_df %>%
					group_by(context,perturb_type,perturb_sign,beep) %>%
					summarise(mean_asyn=mean(asyn),
							  sd_asyn=sd(asyn),
							  mean_pred_asyn=mean(pred_asyn),
							  sd_pred_asyn=sd(pred_asyn),
							  n_asyn=n(),
							  .groups = "drop") %>%
					ungroup()

# invert sign of positive perturbations
data3_mean_inv_df <- data3_mean_df %>%
						mutate(mean_asyn = if_else(perturb_sign=='pos',-mean_asyn,mean_asyn),
							   mean_pred_asyn =
							   		if_else(perturb_sign=='pos',-mean_pred_asyn,mean_pred_asyn),
							   perturb_sign = if_else(perturb_sign=='pos','(-)pos','neg'))
levels_Sinv <- c("neg","(-)pos")
data3_mean_inv_df$perturb_sign <- factor(data3_mean_inv_df$perturb_sign, levels=levels_Sinv)#, ordered=TRUE)

# data3_asym_df <- data3_mean_df %>%
# 					# change sign of negative perturbations so we can compute asym as a difference
# 					# mutate(mean_asyn = if_else(perturb_sign=='neg',-mean_asyn,mean_asyn),
# 					# 	   mean_pred_asyn =
# 					# 	   	if_else(perturb_sign=='neg',-mean_pred_asyn,mean_pred_asyn)) %>%
# 					mutate(mean_asyn = if_else(perturb_sign=='pos',-mean_asyn,mean_asyn),
# 							mean_pred_asyn =
# 						   		if_else(perturb_sign=='pos',-mean_pred_asyn,mean_pred_asyn),
# 							perturb_sign = if_else(perturb_sign=='pos','(-)pos','neg'))
# data3_asym_df$perturb_sign <- factor(data3_asym_df$perturb_sign, levels=levels_Sinv)
# data3_asym_df <- data3_asym_df %>%
data3_asym_df <- data3_mean_inv_df %>%
					group_by(context,perturb_type,beep) %>%
					# NEEDED: previous factor level ordering does not influence row order for diff!!
					arrange(desc(perturb_sign), .by_group=TRUE) %>%
					summarise(asym=diff(mean_asyn),
							  var_pooled=sum((n_asyn-1)*sd_asyn**2)/sum(n_asyn-1),
							  n_pooled=
							  	sum(sd_asyn**2/n_asyn)**2/sum((sd_asyn**2/n_asyn)**2/(n_asyn-1)),
							  ci_asym=1.96*sqrt(var_pooled)/sqrt(n_pooled),
							  asym_pred=diff(mean_pred_asyn),
							  var_pred_pooled=sum((n_asyn-1)*sd_pred_asyn**2)/sum(n_asyn-1),
							  ci_asym_pred=1.96*sqrt(var_pred_pooled)/sqrt(n_pooled),
							  .groups = "drop")

data3_asym_resynch_df <- data3_df %>%
					# keep resynchronization phase only (post-perturbation transient)
					filter(beep>=resynch_start & beep<=resynch_end) %>%
					# average across subjects and beeps
					group_by(context,perturb_type,perturb_sign) %>%
					summarise(mean_asyn=mean(asyn),
							  sd_asyn=sd(asyn),
							  mean_pred_asyn=mean(pred_asyn),
							  sd_pred_asyn=sd(pred_asyn),
							  n_asyn=n(),
							  .groups = "drop") %>%
					# change sign of negative perturbations so we can compute asym as a difference
					# mutate(mean_asyn = if_else(perturb_sign=='neg',-mean_asyn,mean_asyn),
					# 	   mean_pred_asyn =
					# 			if_else(perturb_sign=='neg',-mean_pred_asyn,mean_pred_asyn)) %>%
					mutate(mean_asyn = if_else(perturb_sign=='pos',-mean_asyn,mean_asyn),
							mean_pred_asyn =
								if_else(perturb_sign=='pos',-mean_pred_asyn,mean_pred_asyn),
							perturb_sign = if_else(perturb_sign=='pos','(-)pos','neg')) %>%
# data3_asym_resynch_df$perturb_sign <- factor(data3_asym_resynch_df$perturb_sign, levels=levels_Sinv)
# data3_asym_resynch_df <- data3_asym_resynch_df %>%
					# compute asym
					group_by(context,perturb_type) %>%
					# NEEDED: previous factor level ordering does not influence row order for diff!!
					arrange(perturb_sign, .by_group=TRUE) %>%
					summarise(asym_ave=diff(mean_asyn),
							  var_pooled=sum((n_asyn-1)*sd_asyn**2)/sum(n_asyn-1),
							  n_pooled=
							  	sum(sd_asyn**2/n_asyn)**2/sum((sd_asyn**2/n_asyn)**2/(n_asyn-1)),
							  ci_asym=1.96*sqrt(var_pooled)/sqrt(n_pooled),
							  asym_pred_ave=diff(mean_pred_asyn),
							  var_pred_pooled=sum((n_asyn-1)*sd_pred_asyn**2)/sum(n_asyn-1),
							  ci_asym_pred=1.96*sqrt(var_pred_pooled)/sqrt(n_pooled),
							  .groups = "drop") %>%
					unite(typeXcontext, c(perturb_type, context), sep = "", remove = FALSE)
# set as factor with levels in this specific order
levels_TC <- c("PSpure","PScomb","SCcomb","SCpure")
data3_asym_resynch_df$typeXcontext <- factor(data3_asym_resynch_df$typeXcontext, levels=levels_TC)



```

```{r plot_data, echo=FALSE}


plot_3way_facet_diff <- data3_mean_df %>%
				ggplot(
					aes(x=beep, y=mean_asyn,
						group=interaction(context,perturb_type,perturb_sign),
						color=context,
						shape=perturb_type,
						linetype=perturb_sign)) +
				geom_line() +
				facet_grid(rows=vars(perturb_sign), cols=vars(perturb_type)) +
				geom_point(size=2) +
				scale_x_continuous(limits=c(-3,10))

plot_3way_facet_asym <- data3_mean_inv_df %>%
				ggplot(
					aes(x=beep, y=mean_asyn,
						group=interaction(context,perturb_type,perturb_sign),
						color=context,
						shape=perturb_type,
						linetype=perturb_sign)) +
				geom_line() +
				facet_grid(rows=vars(context), cols=vars(perturb_type)) +
				geom_point(size=2) +
				scale_x_continuous(limits=c(-3,10))

plot_asym <- data3_asym_df %>%
				ggplot(
					aes(x=beep, y=asym,
						group=interaction(context,perturb_type),
						color=context,
						shape=perturb_type)) +
				geom_line() +
				geom_errorbar(aes(x=beep, ymin=asym-ci_asym,
								  ymax=asym+ci_asym, width=0.2)) +
				geom_point() +
				guides(linetype=FALSE) +
				scale_x_continuous(limits=c(-3,10))

plot_asym_resynch <- data3_asym_resynch_df %>%
				ggplot(
					aes(x=typeXcontext, y=asym_ave,
						color=context,
						shape=perturb_type)) +
				geom_errorbar(aes(x=typeXcontext, ymin=asym_ave-ci_asym,
								  ymax=asym_ave+ci_asym, width=0.2)) +
				geom_point() +
				theme(legend.position = "none")

fig1 <- plot_3way_facet_diff
fig2 <- plot_3way_facet_asym
fig3 <- (plot_asym + plot_asym_resynch + plot_layout(ncol = 2, widths = c(2, 1)))

fig1
fig2
fig3

```

```{r fit_model_DIFF_lme4, echo=FALSE}

# select resynchronization phase only
data3_red_df <- data3_df %>% filter(
							beep>=resynch_start & beep<=resynch_end
							)

# specific model: 3rd-order interaction
# main effect of context or any of its interactions
model_diff_3int <- lmer(asyn ~ context + perturb_type + perturb_sign
						+ context:perturb_type
						+ context:perturb_sign
						+ context:perturb_type:perturb_sign
						+ (1|subject),
						data = data3_red_df,
						REML = TRUE) # unbiased estimation of fixed effects
									 # (not appropriate for model comparison)
anova_table_diff_3int <- Anova(model_diff_3int, type="III")
print(anova_table_diff_3int)

# alternative model: up to 2nd-order interactions
model_diff_alt <- lmer(asyn ~ context + perturb_type + perturb_sign
						+ context:perturb_type
						+ context:perturb_sign
						+ perturb_type:perturb_sign
						+ (1|subject),
						data = data3_red_df,
						REML = TRUE) # unbiased estimation of fixed effects
									 # (not appropriate for model comparison)
anova_table_diff_alt <- Anova(model_diff_alt, type="III")
print(anova_table_diff_alt)

anova_table_comp <- anova(model_diff_alt,model_diff_3int, test=TRUE)
print(anova_table_comp)


```

```{r marginal_means_DIFF}

# post-hoc comparisons
model_diff_3int_emm <- emmeans(model_diff_3int, ~ context:perturb_type:perturb_sign)

# contrasts (post-hoc comparisons)
# print estimates and confidence intervals
model_diff_3int_emm_pairs <- pairs(model_diff_3int_emm, simple="context", infer=c(TRUE,TRUE))
print(model_diff_3int_emm_pairs)
# print corrected p-values
model_diff_3int_emm_test <- test(model_diff_3int_emm_pairs, cross.adjust="fdr", type="response")
print(model_diff_3int_emm_test)

# compute confidence intervals
model_diff_3int_emm_test_CI <- model_diff_3int_emm_test %>%
								mutate(LCI = estimate - 1.96*SE,
									   UCI = estimate + 1.96*SE)
print(model_diff_3int_emm_test_CI)


```


```{r fit_model_ASYM_lme4, echo=FALSE}

data3_red_inv_df <- data3_red_df %>%
					# switch sign of negative perturbations
					mutate(asyn = if_else(perturb_sign=='pos',-asyn,asyn))

# specific model: main effect of perturb_sign or any of its interactions
# (asymmetry = difference between signs)
# interaction between perturb_sign, perturb_type and context (perturb_sign has a
# differential effect depending on the type of perturbation AND the context, i.e. pure
# context makes SCs more asymmetrical but PSs less asymmetrical)
model_asym_3int <- lmer(asyn ~ context + perturb_type + perturb_sign
						+ context:perturb_sign
						+ perturb_type:perturb_sign
						+ context:perturb_type:perturb_sign
						+ (1|subject),
						data = data3_red_inv_df,
						REML = TRUE) # unbiased estimation of fixed effects
									 # (not appropriate for model comparison)
anova_table_asym_3int <- Anova(model_asym_3int, type="III")
print(anova_table_asym_3int)


# alternative model: all first-order interactions
model_asym_alt <- lmer(asyn ~ context + perturb_type + perturb_sign
						+ context:perturb_type
						+ context:perturb_sign
						+ perturb_type:perturb_sign
						+ (1|subject),
						data = data3_red_inv_df,
						REML = TRUE) # unbiased estimation of fixed effects
									 # (not appropriate for model comparison)
anova_table_asym_alt <- Anova(model_asym_alt, type="III")
print(anova_table_asym_alt)


# model comparison
anova(model_asym_alt, model_asym_3int, test=TRUE)


```

```{r marginal_means_ASYM}

# post-hoc comparisons
model_asym_3int_emm <- emmeans(model_asym_3int, ~ context:perturb_type:perturb_sign)
model_asym_3int_emm_pairs <- pairs(model_asym_3int_emm, simple="perturb_sign", infer=c(TRUE,TRUE))
model_asym_3int_emm_contrast <- contrast(model_asym_3int_emm_pairs, "pairwise", by=NULL,
										 adjust="sidak")[c(1,2,6),]
model_asym_3int_emm_contrast_CI <- summary(model_asym_3int_emm_contrast)
model_asym_3int_emm_contrast_CI <- model_asym_3int_emm_contrast_CI %>%
								mutate(LCI = estimate - 1.96*SE,
									   UCI = estimate + 1.96*SE)
print(model_asym_3int_emm_contrast_CI)

# comparison between asymmetry of pure conditions
# pure SC is more asymmetrical than pure PS
model_asym_3int_emm_pures <- contrast(model_asym_3int_emm_pairs, "pairwise", by=NULL, adjust=NULL)[5]
model_asym_3int_emm_pures_CI <- summary(model_asym_3int_emm_pures) %>%
								mutate(LCI = estimate - 1.96*SE,
									   UCI = estimate + 1.96*SE)
print(model_asym_3int_emm_pures_CI)


```

